#ifndef _BEBONE_RENDERER_BACKEND_H_
#define _BEBONE_RENDERER_BACKEND_H_

// Todo
#define BEBONE_TYPES_MATRIX_COLUMN_MAJOR_ORDER
#define BEBONE_TYPES_MATRIX4X4_PROJECTION_MATRIX_INVERSE_Y_AXIS
#include "../gfx/gfx.h"
#include "../core/core.h"

#endif
