name: Build, clang win

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Setup Ninja
      uses: ashutoshvarma/setup-ninja@v1.1
      
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        install: make mingw-w64-x86_64-clang

    - name: Prepare Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.2.0
      with:
        vulkan-query-version: 1.3.204.0
        vulkan-components: Vulkan-Headers, Vulkan-Loader
        vulkan-use-cache: true  
    
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Configure the project
      uses: threeal/cmake-action@v1.3.0
      with:
        generator: Ninja
        c-compiler: clang
        cxx-compiler: clang++
        build-dir: submodules/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
