name: Build, clang win

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Setup Ninja
      uses: ashutoshvarma/setup-ninja@v1.1
      
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        install: make mingw-w64-x86_64-clang
        
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja
      env:
        CC: clang
        CXX: clang

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
