name: Build, mingw gcc win

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Setup Ninja
      uses: ashutoshvarma/setup-ninja@v1.1
      
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        install: make mingw-w64-ucrt-x86_64-gcc
    
    - name: Install Vulkan SDK
      uses: jakoch/install-vulkan-sdk-action@v1.0.0
      with:
        vulkan_version: 1.3.231.1
        optional_components: com.lunarg.vulkan.vma
        install_runtime: true
        cache: true
        stripdown: true

    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja
      env:
        CC: gcc
        CXX: g++

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
