name: Windows MinGW Build

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Install Vulkan SDK
      uses: jakoch/install-vulkan-sdk-action@v1.0.0
      with:
        vulkan_version: 1.3.231.1
        optional_components: com.lunarg.vulkan.vma
        install_runtime: true
        cache: true
        stripdown: true

    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Configure CMake
      uses: threeal/cmake-action@v1.3.0
      with:
        generator: Ninja
        c-compiler: gcc
        cxx-compiler: g++
        build-dir: build

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
